import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">

      <body className={`${inter.className} light dark:bg-gray-950 bg-white dark:text-white text-gray-700`}>
        {children}
        
      </body>
    </html>
  );
}
